services:
    _defaults:
        autowire: true
        autoconfigure: true

    cloudflare_turnstile.type:
        class: Zemasterkrom\CloudflareTurnstileBundle\Type\CloudflareTurnstileType
        tags: ["form.type"]
        arguments:
            $sitekey: "%zmkr_cloudflare_turnstile.captcha.sitekey%"

    cloudflare_turnstile.validator:
        class: Zemasterkrom\CloudflareTurnstileBundle\Validator\CloudflareTurnstileCaptchaValidator
        tags: ["validator.constraint_validator"]
        arguments:
            $secretKey: "%zmkr_cloudflare_turnstile.captcha.secret_key%"
            $cloudflareTurnstileErrorManager: "@cloudflare_turnstile.error_manager"

    cloudflare_turnstile.error_manager:
        class: Zemasterkrom\CloudflareTurnstileBundle\ErrorManager\CloudflareTurnstileErrorManager
        arguments:
            $throwOnCoreFailure: "%zmkr_cloudflare_turnstile.error_manager.throw_on_core_failure%"
